const products = [
  {
    title: "Telon circular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R009",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857553/vt0rsioofrtuds3psqg4.jpg",
  },
  {
    title: "Telon circular Sonic",
    description: "Tela set poliester.",
    price: 5500,
    code: "R010",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857552/heevgtxydynyq1djcamt.jpg",
  },
  {
    title: "Telon circular Campeones",
    description: "Tela set poliester.",
    price: 5500,
    code: "R011",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857552/k1mm9bapcwaxsj11fr8t.jpg",
  },
  {
    title: "Telon circular Granja",
    description: "Tela set poliester.",
    price: 5500,
    code: "R012",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857552/ovzzsg9wvl7d7fgszbd4.jpg",
  },
  {
    title: "Telon circular Sirenita",
    description: "Tela set poliester.",
    price: 5500,
    code: "R013",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857552/gdpbbrvljvtowacqcgnc.jpg",
  },
  {
    title: "Telon circular Baby Shark",
    description: "Tela set poliester.",
    price: 5500,
    code: "R014",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857551/ekapx7zgar7ofnqvel2m.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R016",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857882/cx9hwwpfu42ewx19quqt.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R0017",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857881/t6ytlzljb6dhqolh1hp2.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R018",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857880/cwoojkgzpbgdmxg7k8cm.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R019",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857880/cwoojkgzpbgdmxg7k8cm.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R020",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857880/jobmfyp7txqdhdu5pu0f.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R021",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857880/nvvdipid319kd0p3kwu3.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R022",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857879/cgoitnzt9iylgsyqt1eg.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R023",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857878/uvk2r2llriugsoeqb8di.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R024",
    category: "circulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857878/nqx8xfw56q5iz3e9ydxj.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R0025",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857875/cjbtlmxgp5tzkceuz4xf.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R026",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857877/gbmxuvqn3r6kise65j7c.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R027",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857877/kttstyawebn4exeeese5.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R028",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857876/rwia3cawzvyw9aguwrbn.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R029",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857875/rf9pjgqtnw6y1yirs6z0.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R030",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857876/ief3fm1dc8abqq6ri1eo.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R031",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857876/myvnmxpap6fhf3nmwepb.jpg",
  },
  {
    title: "Bandera de egresados",
    description: "Tela set poliester.",
    price: 5500,
    code: "R032",
    category: "banderas",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693857876/pxeqmwunene2pzs1fj81.jpg",
  },
  {
    title: "Telon rectangular Safari",
    description: "Tela set poliester. 150x300",
    price: 8500,
    code: "R001",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853945/zswwegzzakgrqqg1f0dx.jpg",
  },
  {
    title: "Telon rectangular Barbie",
    description: "Tela set poliester. 150x150",
    price: 5500,
    code: "R002",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853945/cdaguvd946jvflo3tuoy.jpg",
  },
  {
    title: "Telon rectangular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R003",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853944/gwbu32sqh416h2jttrmf.jpg",
  },
  {
    title: "Telon rectangular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R004",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853944/gp5s5en94x3je9u7ysyq.jpg",
  },
  {
    title: "Telon rectangular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R005",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853944/k743ppvbxkyjfzyshvev.jpg",
  },
  {
    title: "Telon rectangular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R006",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853944/ici2rngyc5uch93d2aq9.jpg",
  },
  {
    title: "Telon rectangular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R007",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853944/xjefehafrlaufm3xpatb.jpg",
  },
  {
    title: "Telon rectangular",
    description: "Tela set poliester.",
    price: 5500,
    code: "R008",
    category: "rectangulares",
    status: true,
    stock: 100,
    thumbnail:
      "https://res.cloudinary.com/dcxejdzab/image/upload/v1693853944/zfbnpmkmok1tci2ksv56.jpg",
  },
];
export default products;
