paths:
  /api/productsDatabase:
    get:
      summary: Obtener todas los productos
      tags:
        - Productos
      responses:
        "200":
          description: Los productos se obtuvieron de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/productsDatabase/:
    post:
      summary: Crear un producto nuevo en la bd
      tags:
        - Productos
      parameters:
        - name: name
          in: path
          required: true
          description: Nombre del producto
          schema:
            type: string
        - name: description
          in: path
          required: true
          description: Descripcion del producto
          schema:
            type: string
        - name: price
          in: path
          required: true
          description: Precio del producto
          schema:
            type: number
        - name: code
          in: path
          required: true
          description: codigo del producto
          schema:
            type: string
        - name: category
          in: path
          required: true
          description: categoria del producto
          schema:
            type: string
        - name: stock
          in: path
          required: true
          description: stock del producto
          schema:
            type: number
        - name: status
          in: path
          required: true
          description: estado del producto
          schema:
            type: boolean
        - name: thumbnail
          in: path
          required: true
          description: thumbnail del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/PostProducts"
      responses:
        "200":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/productsDatabase/{id}/:
    get:
      summary: Obtener productos por ID
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: id es el id del producto
          schema:
            $type: number
      responses:
        "200":
          description: El productos se obtuvo de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
  /api/productsDatabase/{id}:
    delete:
      summary: borrar productos por ID
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: id es el id del producto a borrar
          schema:
            $type: number
      responses:
        "200":
          description: El producto se elimino de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
    put:
      summary: actualizar productos
      tags:
        - Productos
      parameters:
        - name: id
          in: path
          required: true
          description: Description
          schema:
            $type: number
      responses:
        "200":
          description: El producto se elimino de forma correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error interno del servidor
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id del producto
        titulo:
          type: string
          description: nombre del producto
        descripcion:
          type: string
          description: descripcion del producto
        price:
          type: number
          description: precio del producto
        code:
          type: string
          description: codigo unico del producto
        thumbnail:
          type: String
          description: imagen del producto
      example:
        _id: ObjectId("6462956ccdb11f7f26a847e1")
        titulo: "Remera de algodón"
        descripcion: "Remera de algodón suave y cómoda."
        precio: 12.99,
        code: "P002"
        category: "remeras"
        thumbnail: "https://d3ugyf2ht6aenh.cloudfront.net/stores/943/997/products/boy-beige1-2e3a2fe4fc6ce264d016676887628942-1024-1024.webp"
        stock: "50"
        status: true
  requestBodies:
    PostProducts:
      type: object
      properties:
        titulo:
          type: string
          description: nombre del producto
        descripcion:
          type: string
          description: descripcion del producto
        price:
          type: number
          description: precio del producto
        code:
          type: string
          description: codigo unico del producto
        thumbnail:
          type: String
          description: imagen del producto
      example:
        titulo: "Remera de algodón"
        descripcion: "Remera de algodón suave y cómoda."
        precio: 12,
        code: "p002"
        thumbnail: "https://d3ugyf2ht6aenh.cloudfront.net/stores/943/997/products/boy-beige1-2e3a2fe4fc6ce264d016676887628942-1024-1024.webp"
        category: "remeras"
        stock: 20,
        status: true
